[features]
seeds = false
[programs.localnet]
solana_twitter = "EcPBzAJVchiVnnZJHGbkQHHfMPCbyfVTFetkp9rPA8DC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/sohom/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
